feat: add install command

diff --git a/usystem/bin/usystem b/usystem/bin/usystem
--- a/usystem/bin/usystem
+++ b/usystem/bin/usystem
@@ -29,8 +29,10 @@ declare -r BRANCH='main'
 # functions
 ################################################################################
 function _download() {
+    local LOG_LOCATION="${1}"
+
     umask 022
-    if wget -L https://github.com/TimmerTech/synology-usystem/archive/main.tar.gz -O ${USYSTEM_ROOT_DIR}/usystem.tar.gz -o "${USYSTEM_WORK_DIR}/log/usystem.download.${CLI_EXEC_DATE}.log" > /dev/null 2>&1; then
+    if wget -L https://github.com/TimmerTech/synology-usystem/archive/main.tar.gz -O ${USYSTEM_ROOT_DIR}/usystem.tar.gz -o "${LOG_LOCATION}" > /dev/null 2>&1; then
         return 0
     else
         return 1
@@ -41,6 +43,24 @@ function _download() {
 ################################################################################
 # commands
 ################################################################################
+function create_directories() {
+    # Create directories
+    declare -ra DIRECTORIES=(
+        etc/certs
+        log
+        reports
+        sbin
+    )
+
+    for DIR in "${DIRECTORIES[@]}"; do
+        if [ ! -d "${USYSTEM_WORK_DIR}/${DIR}" ]; then
+            mkdir -p "${USYSTEM_WORK_DIR}/${DIR}" || return 1
+        fi
+    done
+
+    return 0
+}
+
 function repair_help() {
     echo $CLI_NAME repair
     echo
@@ -78,20 +98,24 @@ function repair_permissions() {
 }
 
 function repair() {
+    MSG="Repairing"
     while [ ${#} -gt 0 ]; do
         case $1 in
             -h | --help | help )
                 repair_help
             ;;
+            --install )
+                MSG="Installing"
+            ;;
         esac
     done
 
     if [[ $(/usr/bin/id -u) -ne 0 ]]; then
-        echo "usystem repair must be run as root"
+        echo "'usystem repair' must be run as root"
         exit 1
     fi
 
-    printf "%-32s " "Repairing rc.usystem ..."
+    printf "%-32s " "${MSG} rc.usystem ..."
     if cp "${USYSTEM_WORK_DIR}/etc/rc.usystem" /etc; then
         printf '[OK]\n'
     else
@@ -99,7 +123,7 @@ function repair() {
         exit 1
     fi
 
-    printf "%-32s " "Repairing rc.local ..."
+    printf "%-32s " "${MSG} rc.local ..."
     if cp "${USYSTEM_WORK_DIR}/etc/rc.local" /etc; then
         printf '[OK]\n'
     else
@@ -107,7 +131,7 @@ function repair() {
         exit 1
     fi
 
-    printf "%-32s " "Repairing permissions ..."
+    printf "%-32s " "${MSG} permissions ..."
     if repair_permissions; then
         printf '[OK]\n'
     else
@@ -118,6 +142,10 @@ function repair() {
     # Make sure to start usystem
     "${USYSTEM_WORK_DIR}/etc/rc.usystem" start
 
+    # Repair completed, now link/re-link all usystem resources back to the OS
+    # This will a user to only issue the repair command after a DSM upgrade to
+    # completely restore everything
+    #
     # Link usystem resources to OS
     $(basename "${0}") link
 
@@ -143,7 +171,7 @@ function link() {
     done
 
     if [[ $(/usr/bin/id -u) -ne 0 ]]; then
-        echo "usystem link must be run as root"
+        echo "'usystem link' must be run as root"
         exit 1
     fi
 }
@@ -152,8 +180,8 @@ function install_help() {
     echo $CLI_NAME install
     echo
     echo Description:
-    printf "%-4s%s\n" "" "Repair usystem, used after DSM upgrade or update."
-    printf "%-4s%s\n" "" "This will mount and relink usystem to your Synology"
+    printf "%-4s%s\n" "" "Install usystem"
+    printf "%-4s%s\n" "" "This will install, mount and link usystem to your Synology"
     exit 0
 }
 
@@ -167,12 +195,60 @@ function install() {
     done
 
     if [[ $(/usr/bin/id -u) -ne 0 ]]; then
-        echo "usystem install must be run as root"
+        echo "'usystem install' must be run as root"
         exit 1
     fi
 
-    echo "Downloading..."
-    _download
+    # Create usystem root directory
+    if [ ! -d "${USYSTEM_ROOT_DIR}" ]; then
+        mkdir -p "${USYSTEM_ROOT_DIR}"
+    fi
+
+    if [ -d "${USYSTEM_WORK_DIR}" ]; then
+        echo "${USYSTEM_WORK_DIR} already exists; please use 'usystem upgrade'"
+        exit 1
+    fi
+
+    printf "%-32s " "Downloading usystem ..."
+    DOWNLOAD_LOG="${USYSTEM_ROOT_DIR}/usystem.download.${CLI_EXEC_DATE}.log"
+    if _download "${DOWNLOAD_LOG}"; then
+        printf '[OK]\n'
+
+        # Everything went OK; delete download log
+        rm "${DOWNLOAD_LOG}"
+    else
+        printf '[FAILED]\n'
+        echo "ERROR: Failed to download; see log: ${DOWNLOAD_LOG}"
+        exit 1
+    fi
+
+    printf "%-32s " "Installing ..."
+    EXTRACT_LOG="${USYSTEM_ROOT_DIR}/usystem.install.${CLI_EXEC_DATE}.log"
+    if tar -xvf "${USYSTEM_ROOT_DIR}/usystem.tar.gz" --strip-components=1 -C "${USYSTEM_ROOT_DIR}" > "${EXTRACT_LOG}" 2>&1; then
+        printf '[OK]\n'
+
+        # Everything went ok; delete install log, and downloaded archive
+        rm "${EXTRACT_LOG}"
+        rm "${USYSTEM_ROOT_DIR}/usystem.tar.gz"
+    else
+        printf '[FAILED]\n'
+        echo "ERROR: Failed to extract; see log: ${EXTRACT_LOG}"
+        exit 1
+    fi
+
+    # Create all directories
+    printf "%-32s " "Creating Directories ..."
+    if create_directories; then
+        printf '[OK]\n'
+    else
+        printf '[FAILED]\n'
+        echo "ERROR: Failed to create directories"
+        exit 1
+    fi
+
+    # Directories are created now run repair with hidden parameter to
+    # set the console message to 'Installing'
+    $(basename "${0}") repair --install
 }
 
 function backup_help() {
@@ -194,6 +270,10 @@ function backup() {
 
     umask 022
     rm -f "${USYSTEM_ROOT_DIR}"/usystem.tar.gz
+
+    if [ ! -d "${USYSTEM_ROOT_DIR}/backup" ]; then
+        mkdir -p "${USYSTEM_ROOT_DIR}/backup"
+    fi
 
     printf "%-32s " "Creating backup ..."
     if tar -czf "${USYSTEM_ROOT_DIR}/backup/usystem.backup.${CLI_EXEC_DATE}.tar.gz" --exclude usystem/tmp -C "${USYSTEM_ROOT_DIR}" usystem/; then
@@ -236,20 +316,37 @@ function upgrade() {
     rm -f "${USYSTEM_ROOT_DIR}/usystem.tar.gz"
 
     printf "%-32s " "Downloading upgrade ..."
-    if _download; then
+    DOWNLOAD_LOG="${USYSTEM_WORK_DIR}/log/usystem.download.${CLI_EXEC_DATE}.log"
+    if _download "${DOWNLOAD_LOG}"; then
         printf '[OK]\n'
     else
         printf '[FAILED]\n'
-        echo "ERROR: Failed to download; see log: /usys/log/usystem.download.${CLI_EXEC_DATE}.log"
+        echo "ERROR: Failed to download; see log: ${DOWNLOAD_LOG}"
         exit 1
     fi
 
     printf "%-32s " "Upgrading ..."
-    if tar -xvf "${USYSTEM_ROOT_DIR}/usystem.tar.gz" --strip-components=1 -C "${USYSTEM_ROOT_DIR}" > "${USYSTEM_WORK_DIR}/log/usystem.upgrade.${CLI_EXEC_DATE}.log" 2>&1; then
+    EXTRACT_LOG="${USYSTEM_WORK_DIR}/log/usystem.upgrade.${CLI_EXEC_DATE}.log"
+    if tar -xvf "${USYSTEM_ROOT_DIR}/usystem.tar.gz" --strip-components=1 -C "${USYSTEM_ROOT_DIR}" > "${EXTRACT_LOG}" 2>&1; then
         printf '[OK]\n'
     else
         printf '[FAILED]\n'
+        echo "ERROR: Failed to extract; see log: ${EXTRACT_LOG}"
+
         # TODO: REVERT BACKUP
+
+        # Terminate Upgrade
+        exit 1
+    fi
+
+    # Create all directories
+    printf "%-32s " "Creating Directories ..."
+    if create_directories; then
+        printf '[OK]\n'
+    else
+        printf '[FAILED]\n'
+        echo "ERROR: Failed to create directories"
+        exit 1
     fi
 
     $(basename "${0}") repair
@@ -271,7 +368,7 @@ function main_help() {
     printf "%-4s%-23s %s\n" "" "install" "Install usystem";
     printf "%-4s%-23s %s\n" "" "upgrade" "Upgrade usystem";
     printf "%-4s%-23s %s\n" "" "repair" "Repair usystem";
-    printf "%-4s%-23s %s\n" "" "link" "Link usystem to OS";
+    printf "%-4s%-23s %s\n" "" "link" "Link usystem resources to OS";
 
     exit "${1:-0}";
 }
